Ibw\JobeetBundle\Entity\Affiliate:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        category:
            - NotBlank: ~
        type:
            - NotBlank: ~
            - Choice: { callback: getTypeValues }
        url:
            - Url: ~
        email:
            - NotBlank: ~
            - Email: ~
        company:
            - NotBlank: ~
        position:
            - NotBlank: ~
        location:
            - NotBlank: ~
        description:
            - NotBlank: ~
        how_to_apply:
            - NotBlank: ~
        token:
            - NotBlank: ~
        file:
            - Image: ~