security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
 
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: ibw_jobeet_homepage
            logout:
                path:   /logout
                target: /
 
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
 
    providers:
        main:
            entity: { class: Ibw\JobeetBundle\Entity\User, property: username }
#        in_memory:
#            memory:
#                users:
#                    admin: { password: admin, roles: 'ROLE_ADMIN' }
 
    encoders:
        Ibw\JobeetBundle\Entity\User: sha512