Ibw\JobeetBundle\Entity\User:
    type: entity
#    repositoryClass: Ibw\JobeetBundle\Repository\UserRepository
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255